version: '2'
services:
  postgres:
    image: postgres:latest
    container_name: ds_group_project_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./${APP_ENV}_db_storage:/var/lib/postgresql/data
  redis-stack:
    image: redis/redis-stack
    container_name: ds_group_project_redis
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_GUI_PORT}:8001"
  app:
    build: .
    depends_on:
      - postgres
    container_name: ds_group_project_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./${APP_ENV}_app_storage:/project/app/files-storage
      - ./app/migrations/versions:/project/app/migrations/versions
    develop:
      watch:
        - action: sync
          path: .
          target: /project
networks:
  network1:
    external: true